name: doxygen-deploy

on:
  push:
    branches: [ master ]   # Change to main if your default branch is main

jobs:
  deploy-worksheet5:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Install Doxygen
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      # Step 3: Run Doxygen
      - name: Run Doxygen
        working-directory: ${{ github.workspace }}/Worksheet5
        run: doxygen Doxyfile

      # Step 4: Deploy HTML to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages             # target branch
          folder: ${{ github.workspace }}/Worksheet5/html
